#!/usr/bin/env node
/**
 * Reads data/inventory.json (and optional data/normalization.json), writes build/output/.
 * Encoding: UTF-8. PCRE fragments assume a UTF-8 pattern with the /u flag (e.g. PHP preg_match).
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderMetaConstantsPhp } from "./meta-constants-php.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = join(root, "build", "output");

function cpFromHex(cpHex) {
  const m = /^U\+([0-9A-F]+)$/i.exec(cpHex.trim());
  if (!m) return null;
  return parseInt(m[1], 16);
}

function assertInventory(inv) {
  const seen = new Set();
  for (const row of inv.code_points) {
    const { cp, cp_hex } = row;
    if (typeof cp !== "number" || !Number.isInteger(cp)) {
      throw new Error(`Invalid cp (not integer): ${JSON.stringify(row)}`);
    }
    if (cp < 0 || cp > 0x10ffff) {
      throw new Error(`cp out of range: ${cp}`);
    }
    if (cp >= 0xd800 && cp <= 0xdfff) {
      throw new Error(`Surrogate cp forbidden: ${cp}`);
    }
    const fromHex = cpFromHex(cp_hex);
    if (fromHex !== cp) {
      throw new Error(`cp / cp_hex mismatch: ${cp} vs ${cp_hex} (parsed ${fromHex})`);
    }
    if (seen.has(cp)) {
      throw new Error(`Duplicate cp: ${cp} (${cp_hex})`);
    }
    seen.add(cp);
  }
}

/** PCRE class body: emit code points as \\x{H...} (no surrounding brackets). */
function toPcreClassFragment(codePointsSorted) {
  let s = "";
  for (const cp of codePointsSorted) {
    s += `\\x{${cp.toString(16).toUpperCase()}}`;
  }
  return s;
}

function hashFileContent(buf) {
  return createHash("sha256").update(buf).digest("hex");
}

async function main() {
  const invPath = join(root, "data", "inventory.json");
  const invRaw = await readFile(invPath, "utf8");
  const inv = JSON.parse(invRaw);
  assertInventory(inv);

  const sorted = [...inv.code_points].sort((a, b) => a.cp - b.cp);
  const invOut = {
    ...inv,
    code_points: sorted,
  };

  await mkdir(outDir, { recursive: true });

  const minJson = JSON.stringify(invOut);
  const codePointHexLines = sorted.map((r) => r.cp_hex).join("\n") + "\n";
  const pcreFragment = toPcreClassFragment(sorted.map((r) => r.cp)) + "\n";

  const phpLines = [
    "<?php",
    "declare(strict_types=1);",
    "",
    "/** @return array<int, true> Generated by ipa-unicode-inventory — do not edit. */",
    "return [",
    ...sorted.map((r) => `    0x${r.cp.toString(16).toUpperCase()} => true,`),
    "];",
    "",
  ];
  const phpBody = phpLines.join("\n");

  await writeFile(join(outDir, "inventory.min.json"), minJson, "utf8");
  await writeFile(join(outDir, "code_points.txt"), codePointHexLines, "utf8");
  await writeFile(join(outDir, "pcre-class-fragment.txt"), pcreFragment, "utf8");
  await mkdir(join(outDir, "php"), { recursive: true });
  await writeFile(join(outDir, "php", "AllowedCodePoints.php"), phpBody, "utf8");

  const metaConstantsBody = renderMetaConstantsPhp(inv.meta);
  await writeFile(join(root, "src", "MetaConstants.php"), metaConstantsBody, "utf8");

  const pkgPath = join(root, "package.json");
  let generatorVersion = "0.0.0";
  try {
    const pkg = JSON.parse(await readFile(pkgPath, "utf8"));
    generatorVersion = pkg.version || generatorVersion;
  } catch {
    /* optional */
  }

  const files = {
    "inventory.min.json": hashFileContent(Buffer.from(minJson, "utf8")),
    "code_points.txt": hashFileContent(Buffer.from(codePointHexLines, "utf8")),
    "pcre-class-fragment.txt": hashFileContent(Buffer.from(pcreFragment, "utf8")),
    "php/AllowedCodePoints.php": hashFileContent(Buffer.from(phpBody, "utf8")),
  };

  const manifest = {
    dataset_version: inv.meta.dataset_version,
    schema_version: inv.meta.schema_version,
    files,
    generator: {
      name: "ipa-unicode-inventory",
      version: generatorVersion,
      commit: process.env.GITHUB_SHA || process.env.GIT_COMMIT || "local",
    },
  };
  const manifestStr = JSON.stringify(manifest, null, 2) + "\n";
  await writeFile(join(outDir, "manifest.json"), manifestStr, "utf8");

  console.log(`Wrote build outputs to ${outDir} (${sorted.length} code points).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
