<?php

declare(strict_types=1);

namespace JoshDaugherty\IpaUnicodeInventory;

/**
 * Values from data/inventory.json → meta. Generated by scripts/build.js — do not edit.
 */
final class MetaConstants
{
    public const DATASET_VERSION = '1.2.0';

    public const POLICY_ID = 'ipa-extipa-corpus-inclusive';

    public const SCHEMA_VERSION = '1.0.0';
}
